#--------------------- DB ----------------------
# DB Connection with the uri (host)
client: "mongodb://localhost:27017/"

# db name
db: "aiot_course"

# db collection
col: "sensor_readings"


#--------------------- Dataframe Instantiation ----------------------
# Dataframe columns list
order: ["x-axis (g)", "y-axis (g)", "z-axis (g)", "x-axis (deg/s)", "y-axis (deg/s)", "z-axis (deg/s)"]

rename: ["acc_x", "acc_y", "acc_z","gyr_x", "gyr_y", "gyr_z"]


#--------------------- Data Engineering ----------------------
# sliding window algorithm parameters
sliding_window:
  ws: 30
  overlap: 15
  w_type: "hann"
  w_center: True
  print_stats: False

# window to handle for visualization purposes
x_number: 2

# filtering parameterization
filter:
  order: 5
  wn: 0.1
  type: "lowpass"


#--------------------- Learning ----------------------
# Classifier - Statistical
classifier:
  SVC:
    C: 1
    kernel: "linear"
    gamma: 
  RandomForestClassifier:
    n_estimators: 100
    max_depth:

# Parameter Grid for Fine-tuning, for instance, a Grid Search classifier
fine_tune:
  SVC:
    C: [0.1, 1, 10, 100]
    kernel: ['linear', 'rbf', 'poly']
    gamma: [1, 0.1, 0.01, 0.001]
  RandomForestClassifier:
    n_estimators: [100, 200, 300, 400, 500]
    max_depth: [10, 20, 30, 40, 50]

  cv: 5
  verbose: 0

# Classifier - Neural Network
NeuralNetwork:
  hidden_neurons: 60
  activation: "relu"
  optimizer: "adam"
  loss: "sparse_categorical_crossentropy"
  metrics: ["accuracy", "sparse_categorical_crossentropy", "sparse_categorical_accuracy"]
  fit:
    epochs: 50
    batch: 32
    verbose: 0

random_state: 42
